// public/components/VideoPlayer.vue
<template>
  <div id="video-container">
    <video
      autobuffer
      controls
      v-el:playback>
      <source
        src="./public/assets/bob-ross.mp4"
        type="video/mp4"
      />
    </video>
  </div>
  <captions
    v-on:seek="seek"
    v-on:captions-on="captionsOn">
  </captions>
</template>

<script>

import Captions from './Captions.vue'
import {setTimestamp, setActiveCaption} from '../store/actions'

export default {
  vuex: {
    getters: {
      captions: (state) => state.captions,
      scroll: (state) => state.scroll,
      video: (state) => state.video
    },
    actions: {
      setTimestamp,
      setActiveCaption
    }
  },
  components: {
    Captions
  },
  methods: {
    timeUpdate (e) {
      this.setTimestamp(this.$els.playback.currentTime)
      this.setActiveCaption(this.video.timestamp)
      if (this.scroll) this.$broadcast('update-scroll')
    },
    seek () {
      this.$els.playback.currentTime = this.video.timestamp
    },
    captionsOn (bool) {
      if (bool === false) return this.$els.playback.removeEventListener('timeupdate', this.timeUpdate)
      this.$els.playback.addEventListener('timeupdate', this.timeUpdate)
    }
  }
}

</script>

<style>
#video-container {
  margin-right: auto;
  margin-left: auto;
  text-align: center;
}
</style>

// public/components/VideoPlayer.jsx
import React, { PropTypes } from 'react'
import PureRenderMixin from 'react-addons-pure-render-mixin'
import CaptionsContainer from '../containers/CaptionsContainer.jsx'
import Buttons from './Buttons.jsx'

const videoContainerStyles = {
  marginRight: 'auto',
  marginLeft: 'auto',
  textAlign: 'center'
}

const VideoPlayer = React.createClass({
  mixins: [PureRenderMixin],
  render () {
    return (
      <div>
        <div id='video-container' style={videoContainerStyles}>
          <video autobuffer controls
            onTimeUpdate={(e) => {
              this.props.timeUpdate(e, this.props.captionWindow, this.props.captionsOn, this.props.scroll)
            }}
            ref={(node) => {
              this.player = node
            }}>
            <source
              src='./public/assets/bob-ross.mp4'
              type='video/mp4'
            />
          </video>
        </div>
        <Buttons />
        <CaptionsContainer
          seek={this.props.seek}
        />
      </div>
    )
  },
  componentDidMount () {
    this.props.refPlayer(this.player)
  }
})

VideoPlayer.propTypes = {
  captionsOn: PropTypes.bool.isRequired,
  scroll: PropTypes.bool.isRequired,
  timestamp: PropTypes.number.isRequired,
  timeUpdate: PropTypes.func.isRequired,
  seek: PropTypes.func.isRequired,
  refPlayer: PropTypes.func.isRequired
}

export default VideoPlayer
